try new workflow with louder fail

diff --git a/.github/workflows/deploy_to_rush_admin.yml b/.github/workflows/deploy_to_rush_admin.yml
--- a/.github/workflows/deploy_to_rush_admin.yml
+++ b/.github/workflows/deploy_to_rush_admin.yml
@@ -11,15 +11,26 @@ jobs:
 
     steps:
       - name: Send Webhook
+        id: request  # for reference when checking response status
         env:
           SECRET: ${{ secrets.DEPLOY_WEBHOOK_SECRET }}
         run: |
           BODY='{}'
           TIMESTAMP=$(date +%s)
           SIGNATURE=$(echo -n "$TIMESTAMP$BODY" | openssl dgst -sha256 -hmac "$SECRET" | cut -d " " -f2)
-          curl -X POST https://whatstherush.earth/deploy/python-deployer \
+          response=$(curl -X POST https://whatstherush.earth/deploy/python-deployer \
               -H "Content-Type: application/json" \
               -H "X-Timestamp: $TIMESTAMP" \
               -H "X-Signature: $SIGNATURE" \
-              -d "$BODY"
+              -d "$BODY")
+          echo "Response: $response"
+          status=$(echo "$response" | jq -r '.success')
+          echo "status=$status" >> $GITHUB_OUTPUT
 
+      - name: Check response
+        run: |
+          if [ "${{ steps.request.outputs.status }}" != true ]; then
+            echo "Deployment failed with status=${{ steps.request.outputs.status }}"
+            exit 1
+          fi
+          echo "Deployment succeeded ✅"
